version: "3.3"
services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: trellodb
    ports:
      - 5432:5432
    restart: "always"
    volumes:
      #- ./postgres/data:/docker-entrypoint-initdb.d/
      - ./postgres/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nest:
    depends_on:
      - postgres
    image: node:20
    env_file: 
      - ./purrwebtestcase/.env
    restart: "always"
    volumes:
      - ./purrwebtestcase/:/purrwebtestcase/
    ports:
      - 8000:8000
    working_dir: /purrwebtestcase/
    command: npm install 
    entrypoint: npm run start
    links:
      - "postgres:database"


